### ISSUE TITLE
Author information is lost from merge commits/pull requests

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/mirror#1]
The original author information is lost when using `git svn dcommit`.  I don't think there is anything we can do about this loss using `git svn` however.

**Comment by dtenenba** [comment]
Does the --add-author-from flag help at all?

**Comment by jimhester** [comment]
Yes I guess that would at least store the information on the commit message.

Then you could get the information back from git using `--use-log-author`.

Good find Dan!
