### ISSUE TITLE
clarification of Known Issues section

### ISSUE THREAD

**Issue by nhayden** [Bioconductor/mirror#5]
This is related to PR #4 . With an eye for clarity I think there might be a phrase missing in the italicized Note reference therein, that a user who has fetched or git svn rebase'd in the intervening time will have out-of-sync history.

Overall, I think this paragraph could use clarification since it seems to say "don't fix it by pushing it to public repos", and then says to fix by pushing it to public repos. But maybe it jumps from talking about the GitHub public repos to the svn public repo and I missed it?

**Comment by jimhester** [comment]
I think the best option for all of this is to just do as Paul suggests and
make svn accept any commit one character or more.  That way the commit
criteria will be the same in both cases.

Another thing we could do is have update_remotes.sh also install a local
commit hook to check the commit is 10 characters.  That would also solve
this, and will be what I would suggest if we don't want to modify the svn
hook

**Comment by dtenenba** [comment]
Feel free to change the hook, it's on hedgehog at

/extra/svndata/gentleman/svnroot/bioconductor/hooks/disallow-blank-commit-messages.py

However, if we start seeing a lot of meaningless one-character commit messages, we may want to revisit this.

Dan

----- Original Message -----

**Comment by jimhester** [comment]
Ok I changed it to only reject commits < 1 character long, so we can safely
remove that section from the documentation.

**Comment by dtenenba** [comment]
It might still be valuable to have it in there, because (as Nate points out) there are other reasons that the two repos could get out of sync, such as an issue with the post-commit hook, or who knows what else. So it would be good to know what to do in that case.

Dan

----- Original Message -----

**Comment by nhayden** [comment]
Yes, I think it's valuable as a stand-alone item for what to do when the public svn and GitHub repos get out of sync, and the potential repercussions if someone has pulled from your repository in the intervening time.
