### ISSUE TITLE
Git clone not working - git clone https://github.com/Bioconductor-mirror/REPO 

### ISSUE THREAD

**Issue by nrineau** [Bioconductor/mirror#8]
Hi,

I try to clone the repo on local The command:

git clone https://github.com/Bioconductor-mirror/REPO
or 
git clone https://github.com/Bioconductor/REPO.

The commend retrun the page is not exists.:

 git clone https://github.com/Bioconductor/REPO
Initialized empty Git repository in /opt/REPO/.git/
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/Bioconductor/REPO/info/refs

Do you have idea?

Regards,

**Comment by b-long** [comment]
Hi @nrineau ,

Presumably, the text you're reading is meant to be an example.  So, rather than using : 

```
git clone https://github.com/Bioconductor-mirror/REPO
or 
git clone https://github.com/Bioconductor/REPO
```

You should point to an actual package : 

```
git clone https://github.com/Bioconductor-mirror/BiocParallel.git
or
git clone https://github.com/Bioconductor/BiocParallel.git
```

Can you tell me where you found that text?  Hopefully we can add some clarification to the text.

**Comment by jimhester** [comment]
@b-long likely it was [https://github.com/Bioconductor/bioconductor.org/content/developers/how-to/git-mirrors.md#scenario-1-use-git-locally-no-github-repository](https://github.com/Bioconductor/bioconductor.org/blob/b351580bde74f97dc09ef53933065453125fc146/content/developers/how-to/git-mirrors.md#scenario-1-use-git-locally-no-github-repository)

**Comment by b-long** [comment]
@jimhester Ah, thanks.  I think you're right!

**Comment by b-long** [comment]
@nrineau Please let us know if you're having any further difficulty.  Closing this issue in the meantime.
